@startuml
hide footbox
alt 成功
    "小新" -> "父亲广志": 要零花钱10元
  else 失败
    "小新" <- "父亲广志": 反遭挨骂
    group 继续要钱
      "父亲广志" -> "母亲美伢" : 别给小新零花钱
      loop 30 次
        "小新" -> "父亲广志": 给我零花钱..
      end
      loop 35 次
         "小新" -> "母亲美伢": 给我零花钱..
      end
      "父亲广志" <-> "母亲美伢" : 要不就给他点吧？
    end
  else 失败
    "小新" -> "父亲广志": 我要补习班费
end
@enduml