@startuml
title 计划单下发时序图
actor 页面手动下发 as X

系统自动下发 -> 单据转换与执行模块: 定时执行计划转通知下发任务
activate 单据转换与执行模块

X -> 单据转换与执行模块: 启动计划转通知下发任务
单据转换与执行模块 -> 单据转换与执行模块: 2.1异步任务启动
activate 单据转换与执行模块
单据转换与执行模块 -> 单据转换与执行模块: 2.2查询待下发的计划单

单据转换与执行模块 -> 入仓决策: 2.2.1调用入仓决策，校验合法性
activate 入仓决策
入仓决策 --> 单据转换与执行模块:
deactivate 入仓决策

单据转换与执行模块 -> 单据转换与执行模块: 2.3根据配置的下发规则合单

单据转换与执行模块 -> 采购执行: 2.4下发采购执行，返回jobId
activate 采购执行
采购执行 --> 单据转换与执行模块:
deactivate 采购执行

采购执行 -> 单据转换与执行模块: 3.异步消息，通知创单成功
单据转换与执行模块 -> 单据转换与执行模块: 3.1修改状态下发成功状态
采购执行 -> 单据转换与执行模块: 4.异步消息，通知创单失败

单据转换与执行模块 -> 单据转换与执行模块: 5.根据错误类型，重试
deactivate 单据转换与执行模块
单据转换与执行模块 -> 采购执行: 6.系统错误，重试下发

deactivate 单据转换与执行模块

@enduml

