@startuml
hide footbox
title 计划单系统交互时序图
Schedulex定时任务 -> 计划单业务实现类: 每隔10分钟执行自动审核逻辑
activate Schedulex定时任务

note over 计划单业务实现类: 是否需要自动审核
activate 计划单业务实现类
计划单业务实现类 -> 配置与参数校验中心:依据配置中心，规则中心，参数系统做配置与参数校验
activate 配置与参数校验中心
alt 配置与参数校验有效
    配置与参数校验中心 --> 计划单业务实现类 : 需要自动审核
else 配置与参数校验无效
    配置与参数校验中心 --> 计划单业务实现类: 不需要自动审核
    deactivate 配置与参数校验中心
    计划单业务实现类 --> Schedulex定时任务: 自动审核失败
end


== 分隔符 ==
activate 计划单业务实现类
note over 计划单业务实现类: 决策是否自动审核通过
计划单业务实现类 -> 自动审核决策中心: 获取自动审核通过的规则列表，决策是否自动审核通过
activate 自动审核决策中心
alt 决策自动审核通过
    自动审核决策中心 --> Schedulex定时任务: 决策计划单自动审核通过
    Schedulex定时任务 -> 计划单审核执行中心: 更新计划单据状态,权限校验
    activate 计划单审核执行中心
    计划单审核执行中心 --> 计划单审核执行中心: 计划单状态变更
    计划单审核执行中心 --> Schedulex定时任务: 自动审核成功
    deactivate 计划单审核执行中心
else 决策自动审核不通过
    自动审核决策中心 --> 计划单业务实现类: 自动审核终止
    deactivate 自动审核决策中心
    计划单业务实现类 --> Schedulex定时任务: 决策计划单自动审核不通过
end



deactivate Schedulex定时任务

@enduml

